-- MySQL Script generated by MySQL Workbench
-- Fri May  6 12:58:53 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Tarifas
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Tarifas` ;

-- -----------------------------------------------------
-- Schema Tarifas
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Tarifas` DEFAULT CHARACTER SET utf8 ;
USE `Tarifas` ;

-- -----------------------------------------------------
-- Table `Tarifas`.`Cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Tarifas`.`Cliente` ;

CREATE TABLE IF NOT EXISTS `Tarifas`.`Cliente` (
  `idCliente` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `descuento` DECIMAL(10) NULL,
  `nivel` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Tarifas`.`Tarifa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Tarifas`.`Tarifa` ;

CREATE TABLE IF NOT EXISTS `Tarifas`.`Tarifa` (
  `idTarifa` INT NOT NULL AUTO_INCREMENT,
  `pais_origen` VARCHAR(45) NULL,
  `pais_destino` VARCHAR(45) NULL,
  `Cliente_idCliente` INT NOT NULL,
  PRIMARY KEY (`idTarifa`, `Cliente_idCliente`),
  INDEX `fk_Tarifa_Cliente_idx` (`Cliente_idCliente` ASC) VISIBLE,
  CONSTRAINT `fk_Tarifa_Cliente`
    FOREIGN KEY (`Cliente_idCliente`)
    REFERENCES `Tarifas`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Tarifas`.`Pais`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Tarifas`.`Pais` ;

CREATE TABLE IF NOT EXISTS `Tarifas`.`Pais` (
  `idPais` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `region` VARCHAR(45) NULL,
  `monto_tarifa` DECIMAL(10) NULL,
  `Tarifa_idTarifa` INT NOT NULL,
  `Tarifa_Cliente_idCliente` INT NOT NULL,
  PRIMARY KEY (`idPais`, `Tarifa_idTarifa`, `Tarifa_Cliente_idCliente`),
  INDEX `fk_Pais_Tarifa1_idx` (`Tarifa_idTarifa` ASC, `Tarifa_Cliente_idCliente` ASC) VISIBLE,
  CONSTRAINT `fk_Pais_Tarifa1`
    FOREIGN KEY (`Tarifa_idTarifa` , `Tarifa_Cliente_idCliente`)
    REFERENCES `Tarifas`.`Tarifa` (`idTarifa` , `Cliente_idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


-- INSERTS --
-- -----------------------------------------------------
-- Table `Tarifas`.`Cliente`
-- -----------------------------------------------------

INSERT INTO `Tarifas`.`Cliente` (idCliente, nombre, apellido, descuento, nivel) VALUES (default, "Gizeh", "Garcia", 10.00, 1);
SELECT * FROM `Tarifas`.`Cliente`;


-- -----------------------------------------------------
-- Table `Tarifas`.`Tarifa`
-- -----------------------------------------------------
INSERT INTO `Tarifas`.`Tarifa` (idTarifa, pais_origen, pais_destino, Cliente_idCliente) VALUES (default, "Guatemala", "USA",1 );
SELECT * FROM `Tarifas`.`Tarifa`;

-- -----------------------------------------------------
-- Table `Tarifas`.`Pais`
-- -----------------------------------------------------

INSERT INTO `Tarifas`.`Pais` (idPais, nombre, region, monto_tarifa, Tarifa_idTarifa, Tarifa_Cliente_idCliente) VALUES (default, "Guatemala", "Centroamerica", 100.00, 1, 1);
SELECT * FROM `Tarifas`.`Pais`;